name: dumb_parser
description: The dumbest parser. Don't use this. It's easy though.
# version: 0.1.0
# homepage: https://www.example.com
# author: Dana <matterovermind@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

#dependencies:

dev_dependencies:
  test: ^1.0.0
